---

- hosts: all
  become: true

  tasks:
  - name: remove firewalld
    yum:
      name: firewalld
      state: absent

  - name: install net-tools, curl and wget
    yum:
      name:
        - net-tools
        - curl
        - wget
      state: present

  - name: update /etc/yum.repos.d/wazuh.repo
    lineinfile:
      dest: /etc/yum.repos.d/wazuh.repo
      state: present
      line: "{{ item }}"
    with_items:
      - '[wazuh_repo]'
      - 'gpgcheck=1'
      - 'gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH'
      - 'enabled=1'
      - 'name=Wazuh repository'
      - 'baseurl=https://packages.wazuh.com/3.x/yum/'
      - 'protect=1'

  - name: install wazuh-manager,python-setuptools,python-cryptography
    yum:
      name:
        - wazuh-manager
        - python-setuptools
        - python-cryptography
      state: present

  - name:  download splunkforwarder
    shell: wget -O splunkforwarder-7.1.3-51d9cac7b837-linux-2.6-x86_64.rpm 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.1.3&product=universalforwarder&filename=splunkforwarder-7.1.3-51d9cac7b837-linux-2.6-x86_64.rpm&wget=true'

  - name: install splunkforwarder
    yum:
      name: splunkforwarder-7.1.3-51d9cac7b837-linux-2.6-x86_64.rpm
      state: present

  - name:  props.conf
    shell: curl -so /opt/splunkforwarder/etc/system/local/props.conf https://raw.githubusercontent.com/wazuh/wazuh/3.6/extensions/splunk/props.conf

  - name:  inputs.conf
    shell: curl -so /opt/splunkforwarder/etc/system/local/inputs.conf https://raw.githubusercontent.com/wazuh/wazuh/3.6/extensions/splunk/inputs.conf

  - name:  set hostname
    shell: sed -i "s:MANAGER_HOSTNAME:$(hostname):g" /opt/splunkforwarder/etc/system/local/inputs.conf

# accept license
## /opt/splunkforwarder/bin/splunk start --accept-license

# forward to index
# /opt/splunkforwarder/bin/splunk add forward-server 192.168.1.195:9997

# restart service
# /opt/splunkforwarder/bin/splunk restart

  - name: daemon-reload
    systemd: daemon_reload=yes

  - name: enable wazuh-manager
    systemd:
      name: wazuh-manager
      enabled: yes

  - name:  wazuh cluster config1
    shell: sed -i 's:<node_name>node01</node_name>:<node_name>node02</node_name>:g' /var/ossec/etc/ossec.conf

  - name:  wazuh cluster config2
    shell: sed -i 's:<key></key>:<key>{{ key }}</key>:g' /var/ossec/etc/ossec.conf

  - name:  wazuh cluster config3
    shell: sed -i 's:<node>NODE_IP</node>:<node>{{ node_ip }}</node>:g' /var/ossec/etc/ossec.conf

  - name:  wazuh cluster config4
    shell: sed -i 's:<node_type>master</node_type>:<node_type>client</node_type>:g' /var/ossec/etc/ossec.conf

  - name:  wazuh cluster config5
    shell: sed -i 's:<disabled>yes</disabled>:<disabled>no</disabled>:g' /var/ossec/etc/ossec.conf

  - name: restart wazuh-manager
    systemd:
      name: wazuh-manager
      state: restarted